version: '3'

services:
  backend:
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    volumes:
      - ../backend:/app
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/dev.Dockerfile
    volumes:
      - ../frontend/src:/app/src
